#!/usr/bin/env bash

if [ "x$BASH_SOURCE" != "x" ]; then
	d=`dirname $BASH_SOURCE`
else
	d=`dirname $0`
fi

basedir=`(cd "$d"; pwd)`

if [ -z "$PROJ_BASE" -o "$PROJ_BASE" != "$basedir" ]; then
	PROJ_BASE="$basedir"
	export PROJ_BASE

	if [ "x$LABEL" != "x" ]; then
		LABEL=`(basename "$PROJ_BASE")`
	fi

	PATH=$PROJ_BASE/bin:$PATH
	export PATH

	. $PROJ_BASE/venv/bin/activate

	PYTHONPATH=$PROJ_BASE/src

	PS1="[$LABEL]"`echo $PS1 | sed -e 's/^(venv)//'`" "
	envprompt ()
	{
		PS1="[$LABEL] $PS1"
	}
	if [ ! -z "$PROMPT_COMMAND" ]; then
		export PROMPT_COMMAND="$PROMPT_COMMAND; envprompt"
	fi
fi


if [ "x$1" != "x" ]; then
	exec "$@"
fi
